### ISSUE TITLE
T4MVC.tt generation failed

### ISSUE THREAD

**Issue by farhadala** [T4MVC/T4MVC#110]
I work on an ASP.NET MVC Core App project with full .net support (4.6.2).
When I add T4MVC with Nuget Package Manager window, T4MVC.tt file does not generate automatically
I create an ASP.NET MVC project, and I don't have any problem.
If I add T4MVC.tt file manually to my project, I get this error when click on 'Run Custom Tool':

Running transformation: System.Runtime.InteropServices.COMException (0x80041FEB): There is no editor available for 'D:\Project\MyWebsite\T4MVC\T4MVC.tt'.

Make sure the application for the file type (.tt) is installed.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ErrorHandler.ThrowOnFailure(Int32 hr)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.FileDocumentManager.Open(SimpleHierarchyNode projectItem, Boolean openWith, UInt32 editorFlags, Guid& editorType, String physicalView, Guid& logicalView, IntPtr docDataExisting, IVsWindowFrame& windowFrame, WindowFrameShowAction windowFrameAction)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.FileDocumentManager.Open(SimpleHierarchyNode projectItem, Boolean openWith, Guid logicalView, IVsWindowFrame& frame, WindowFrameShowAction windowFrameAction)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItem.<>c__DisplayClass55_0.<Open>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.<>c__DisplayClass70_0.<<ExecuteSynchronously>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProject.ExecuteSynchronously(Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAProjectItem.Open(String ViewKind)
   at EnvDTE.ProjectItem.Open(String ViewKind)
   at Microsoft.VisualStudio.TextTemplatingB79BF789C3FE8C8C7DD5BAAFE2B8C6436AF7B6B74EEED23554C9C2CBA7216A6B7081ED167040EEE8E53675322B41DE85D1D2932B2A817215E48EB34AB6218FDB.GeneratedTextTransformation.XmlSettings.Init(ITextTemplatingEngineHost host) in D:\Project\MyWebsite\T4MVC\T4MVC.tt:line 2577
   at Microsoft.VisualStudio.TextTemplatingB79BF789C3FE8C8C7DD5BAAFE2B8C6436AF7B6B74EEED23554C9C2CBA7216A6B7081ED167040EEE8E53675322B41DE85D1D2932B2A817215E48EB34AB6218FDB.GeneratedTextTransformation.XmlSettings.Load[T](ITextTemplatingEngineHost host) in D:\Project\MyWebsite\T4MVC\T4MVC.tt:line 2550
   at Microsoft.VisualStudio.TextTemplatingB79BF789C3FE8C8C7DD5BAAFE2B8C6436AF7B6B74EEED23554C9C2CBA7216A6B7081ED167040EEE8E53675322B41DE85D1D2932B2A817215E48EB34AB6218FDB.GeneratedTextTransformation.MvcSettings.Load(ITextTemplatingEngineHost host) in D:\Project\MyWebsite\T4MVC\T4MVC.tt:line 2230
   at Microsoft.VisualStudio.TextTemplatingB79BF789C3FE8C8C7DD5BAAFE2B8C6436AF7B6B74EEED23554C9C2CBA7216A6B7081ED167040EEE8E53675322B41DE85D1D2932B2A817215E48EB34AB6218FDB.GeneratedTextTransformation.TransformText() in D:\Project\MyWebsite\T4MVC\T4MVC.tt:line 39	Boom.Website	D:\Project\MyWebsite\T4MVC\T4MVC.tt	2577

**Comment by davidebbo** [comment]
T4MVC does not support ASP.NET Core. But take a look at R4MVC: https://github.com/T4MVC/R4MVC
