### ISSUE TITLE
System.ArgumentException: Value does not fall within the expected range.

### ISSUE THREAD

**Issue by cblaze22** [T4MVC/T4MVC#144]
We keep getting this message in our T4MVC generated action links.  We aren't sure why it's happening as it's hard to track.  Is there any clue from the stack trace on what the isse could be?  The server variable IIS_WasUrlRewritten seems to be empty from our logs.

```
System.ArgumentException: Value does not fall within the expected range.

Generated: Wed, 06 Sep 2023 00:05:45 GMT

System.Web.HttpException (0x80004005): Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'. ---> System.ArgumentException: Value does not fall within the expected range.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Web.Hosting.IIS7WorkerRequest.GetServerVariableInternal(String name)
   at System.Web.WebPages.UrlRewriterHelper.WasThisRequestRewritten(HttpContextBase httpContext)
   at System.Web.WebPages.UrlUtil.GenerateClientUrlInternal(HttpContextBase httpContext, String contentPath)
   at System.Web.WebPages.UrlUtil.GenerateClientUrl(HttpContextBase httpContext, String contentPath)
   at System.Web.Mvc.UrlHelper.GenerateUrl(String routeName, String actionName, String controllerName, RouteValueDictionary routeValues, RouteCollection routeCollection, RequestContext requestContext, Boolean includeImplicitMvcValues)
   at System.Web.Mvc.UrlHelper.GenerateUrl(String routeName, String actionName, String controllerName, String protocol, String hostName, String fragment, RouteValueDictionary routeValues, RouteCollection routeCollection, RequestContext requestContext, Boolean includeImplicitMvcValues)
   at System.Web.Mvc.UrlHelper.RouteUrl(String routeName, RouteValueDictionary routeValues, String protocol, String hostName)
   at System.Web.Mvc.T4Extensions.Action(UrlHelper urlHelper, ActionResult result)
   at Tournaments.Models.ViewModels.EventUrls.get_HomeUrl() in E:\Development\Exposure\Development\Websites\Tournaments\Models\ViewModels\EventUrls.cs:line 56
   at ASP._Page_Views_Event_Controls_EventHeader_cshtml.Execute() in C:\Sites\ExposureBasketball\Production\Views\Event\Controls\EventHeader.cshtml:line 5
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
```

**Comment by davidebbo** [comment]
I'm guessing that this is a general MVC question, not directly related to T4MVC. See for instance https://stackoverflow.com/questions/30514551/exception-value-does-not-fall-within-the-expected-range-in-asp-net-mvc-contro

**Comment by cblaze22** [comment]
You are correct but it's only happening on T4MVC created links so I thought I would post here.  Those links aren't async which that post is getting at.

**Comment by davidebbo** [comment]
I don't know what's going on, but in the end, T4MVC just makes a call to `UrlHelper.RouteUrl`. As a test, I'd suggest trying to make the same call directly instead of through T4MVC. If the behavior is the same, we'll know it's not T4MVC specific.

When it comes down to it, T4MVC is mostly a typing aid, but it just turns around and calls MVC.
