### ISSUE TITLE
Visual Sudio 2015 RC support

### ISSUE THREAD

**Issue by bschapendonk** [T4MVC/T4MVC#24]
Running "Run Custom Tool" on T4MVC.tt in Visual Studio 2015 RC gives the following stack-trace

T4MVC version 3.15.0

```
Severity    Code    Description Project File    Line
Error       Running transformation: System.NotImplementedException: Not implemented (Exception from HRESULT: 0x80004001 (E_NOTIMPL))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.CodeModelProjectCache.GetOrCreateFileCodeModel(String fileName, Object parent)
   at Microsoft.VisualStudio.LanguageServices.CSharp.ProjectSystemShim.CSharpProjectShimWithServices.CreateFileCodeModel(String fileName, Object parent, FileCodeModel& ppFileCodeModel)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.ExternalElements.ExternalCodeFunction.get_FunctionKind()
   at EnvDTE80.CodeFunction2.get_FunctionKind()
   at Microsoft.VisualStudio.TextTemplating59D8BD58E2AAFEC54BEEED2B20AA268C82516E251D6FB4A91083F30BA7EC5FB8438BF5C6027B666552489BE97E29A9D259461A2CBBB1BF9A9634822E6006BB0E.GeneratedTextTransformation.ResultTypeInfo.<.ctor>b__69(CodeFunction2 f) in d:\topicus\findesk-default\src\TFiN.WebApplication\T4MVC.tt:line 2100
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.TextTemplating59D8BD58E2AAFEC54BEEED2B20AA268C82516E251D6FB4A91083F30BA7EC5FB8438BF5C6027B666552489BE97E29A9D259461A2CBBB1BF9A9634822E6006BB0E.GeneratedTextTransformation.ResultTypeInfo..ctor(CodeTypeRef codeType) in d:\topicus\findesk-default\src\TFiN.WebApplication\T4MVC.tt:line 2099
   at Microsoft.VisualStudio.TextTemplating59D8BD58E2AAFEC54BEEED2B20AA268C82516E251D6FB4A91083F30BA7EC5FB8438BF5C6027B666552489BE97E29A9D259461A2CBBB1BF9A9634822E6006BB0E.GeneratedTextTransformation.ProcessControllerActionMethods(ControllerInfo controllerInfo, CodeClass2 current) in d:\topicus\findesk-default\src\TFiN.WebApplication\T4MVC.tt:line 890
   at Microsoft.VisualStudio.TextTemplating59D8BD58E2AAFEC54BEEED2B20AA268C82516E251D6FB4A91083F30BA7EC5FB8438BF5C6027B666552489BE97E29A9D259461A2CBBB1BF9A9634822E6006BB0E.GeneratedTextTransformation.ProcessControllerType(CodeClass2 type, AreaInfo area, DateTime controllerLastWriteTime) in d:\topicus\findesk-default\src\TFiN.WebApplication\T4MVC.tt:line 771
   at Microsoft.VisualStudio.TextTemplating59D8BD58E2AAFEC54BEEED2B20AA268C82516E251D6FB4A91083F30BA7EC5FB8438BF5C6027B666552489BE97E29A9D259461A2CBBB1BF9A9634822E6006BB0E.GeneratedTextTransformation.ProcessControllersRecursive(ProjectItem projectItem, AreaInfo area) in d:\topicus\findesk-default\src\TFiN.WebApplication\T4MVC.tt:line 699
   at Microsoft.VisualStudio.TextTemplating59D8BD58E2AAFEC54BEEED2B20AA268C82516E251D6FB4A91083F30BA7EC5FB8438BF5C6027B666552489BE97E29A9D259461A2CBBB1BF9A9634822E6006BB0E.GeneratedTextTransformation.ProcessControllersRecursive(ProjectItem projectItem, AreaInfo area) in d:\topicus\findesk-default\src\TFiN.WebApplication\T4MVC.tt:line 684
   at Microsoft.VisualStudio.TextTemplating59D8BD58E2AAFEC54BEEED2B20AA268C82516E251D6FB4A91083F30BA7EC5FB8438BF5C6027B666552489BE97E29A9D259461A2CBBB1BF9A9634822E6006BB0E.GeneratedTextTransformation.ProcessAreaControllers(ProjectItems areaFolderItems, AreaInfo area, ProjectItem areaFolder) in d:\topicus\findesk-default\src\TFiN.WebApplication\T4MVC.tt:line 654
   at Microsoft.VisualStudio.TextTemplating59D8BD58E2AAFEC54BEEED2B20AA268C82516E251D6FB4A91083F30BA7EC5FB8438BF5C6027B666552489BE97E29A9D259461A2CBBB1BF9A9634822E6006BB0E.GeneratedTextTransformation.ProcessArea(ProjectItem areaFolder, AreaInfo existingArea) in d:\topicus\findesk-default\src\TFiN.WebApplication\T4MVC.tt:line 633
   at Microsoft.VisualStudio.TextTemplating59D8BD58E2AAFEC54BEEED2B20AA268C82516E251D6FB4A91083F30BA7EC5FB8438BF5C6027B666552489BE97E29A9D259461A2CBBB1BF9A9634822E6006BB0E.GeneratedTextTransformation.ProcessAreas(Project project) in d:\topicus\findesk-default\src\TFiN.WebApplication\T4MVC.tt:line 608
   at Microsoft.VisualStudio.TextTemplating59D8BD58E2AAFEC54BEEED2B20AA268C82516E251D6FB4A91083F30BA7EC5FB8438BF5C6027B666552489BE97E29A9D259461A2CBBB1BF9A9634822E6006BB0E.GeneratedTextTransformation.PrepareDataToRender(TextTransformation tt) in d:\topicus\findesk-default\src\TFiN.WebApplication\T4MVC.tt:line 556
   at Microsoft.VisualStudio.TextTemplating59D8BD58E2AAFEC54BEEED2B20AA268C82516E251D6FB4A91083F30BA7EC5FB8438BF5C6027B666552489BE97E29A9D259461A2CBBB1BF9A9634822E6006BB0E.GeneratedTextTransformation.TransformText() in d:\topicus\findesk-default\src\TFiN.WebApplication\T4MVC.tt:line 40  TFiN.WebApplication d:\topicus\findesk-default\src\TFiN.WebApplication\T4MVC.tt 2100
```

**Comment by davidebbo** [comment]
I just tried and was not able to repro this with my sample solution: https://github.com/davidebbo/T4MVCSampleApp. Questions:
- does it happen consistently for you?
- does it happen for you with my test solution?
- if not, then can you share a solution where it does happen?

**Comment by bevanblackie** [comment]
I'm also having the same issue consistently.  I tried the sample solution in VS 2015 RC but could not replicate the issue.

Unfortunately I can't share the solution that has the issue for me.  I'll play around with your example to see if I can "break" it.

**Comment by davidebbo** [comment]
From the stack, there is a specific function that's throwing it off. You could try adding a catch/rethrow with more info around that line (2100 from the stack) so you get the function name. Maybe something will jump out.

**Comment by bevanblackie** [comment]
It appears this line fails:

manager.Process(settings.SplitIntoMultipleFiles); (around line 430 before I put in my catches) 

The caught exception isn't overlly helpful, "Error HRESULT E_FAIL has been returned from a call to a COM component."

**Comment by davidebbo** [comment]
Does your stack look like the one from @bschapendonk? In his case, the failure is happening in this code around line 2100:

```
    var ctor = _codeType.CodeType.Members.OfType<CodeFunction2>()
        .Where(f => f.FunctionKind == vsCMFunction.vsCMFunctionConstructor)
        .OrderBy(f => f.Parameters.Count)
        .FirstOrDefault();
```

Specifically, it's accessing the `f.FunctionKind` property that throws. To get more info, just write a small GetFunctionKind() wrapper that call this property and can throw a better exception with the function info.

If your stack is **not** the same, then please post the stack your getting (preferably with the unmodified template so line numbers match).

**Comment by bevanblackie** [comment]
I believe I have found the problem and have been able to replicate it in your sample app.  If you have an MVC action that returns JsonResult it throws the exception.

**Comment by davidebbo** [comment]
Yes, I can repro. And I see this has come up earlier [here](https://t4mvc.codeplex.com/discussions/542192).

We need to isolate and report to VS team.

**Comment by davidebbo** [comment]
I put in a workaround to ignore `FunctionKind` exception. It seems they could happen even in 2013, but due to arbitrary ordering differences we were not hitting this.

**Can everyone please verify with 3.15.1?**

**Comment by bschapendonk** [comment]
Hi,
 I can confirm that 3.15.1 works for me on VS 2015 RC.

Thanks.

**Comment by q42jaap** [comment]
3.15.4 crashes for me with the latest VS2015 RC:

```
Error       Running transformation: System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.ExternalElements.ExternalCodeFunction.get_FunctionKind()
   at EnvDTE80.CodeFunction2.get_FunctionKind()
   at Microsoft.VisualStudio.TextTemplatingB4E831D51904A75E37FAD606F60DF3D4ECAF9D36C4B60E340FDEA400F1A35469B574C0754C7AF2E8BE452A26F89DDA24B274CEB9E353BE914CA7ACC51EF3DA01.GeneratedTextTransformation.ResultTypeInfo.<.ctor>b__65(CodeFunction2 f) in c:\Users\Jaap\Projects\MyProject\src\MyProject.Web\Generated\T4MVC.tt:line 1886
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.TextTemplatingB4E831D51904A75E37FAD606F60DF3D4ECAF9D36C4B60E340FDEA400F1A35469B574C0754C7AF2E8BE452A26F89DDA24B274CEB9E353BE914CA7ACC51EF3DA01.GeneratedTextTransformation.ResultTypeInfo..ctor(CodeTypeRef codeType) in c:\Users\Jaap\Projects\MyProject\src\MyProject.Web\Generated\T4MVC.tt:line 1885
   at Microsoft.VisualStudio.TextTemplatingB4E831D51904A75E37FAD606F60DF3D4ECAF9D36C4B60E340FDEA400F1A35469B574C0754C7AF2E8BE452A26F89DDA24B274CEB9E353BE914CA7ACC51EF3DA01.GeneratedTextTransformation.ProcessControllerActionMethods(ControllerInfo controllerInfo, CodeClass2 current) in c:\Users\Jaap\Projects\MyProject\src\MyProject.Web\Generated\T4MVC.tt:line 878
   at Microsoft.VisualStudio.TextTemplatingB4E831D51904A75E37FAD606F60DF3D4ECAF9D36C4B60E340FDEA400F1A35469B574C0754C7AF2E8BE452A26F89DDA24B274CEB9E353BE914CA7ACC51EF3DA01.GeneratedTextTransformation.ProcessControllerType(CodeClass2 type, AreaInfo area, DateTime controllerLastWriteTime) in c:\Users\Jaap\Projects\MyProject\src\MyProject.Web\Generated\T4MVC.tt:line 759
   at Microsoft.VisualStudio.TextTemplatingB4E831D51904A75E37FAD606F60DF3D4ECAF9D36C4B60E340FDEA400F1A35469B574C0754C7AF2E8BE452A26F89DDA24B274CEB9E353BE914CA7ACC51EF3DA01.GeneratedTextTransformation.ProcessControllersRecursive(ProjectItem projectItem, AreaInfo area) in c:\Users\Jaap\Projects\MyProject\src\MyProject.Web\Generated\T4MVC.tt:line 691
   at Microsoft.VisualStudio.TextTemplatingB4E831D51904A75E37FAD606F60DF3D4ECAF9D36C4B60E340FDEA400F1A35469B574C0754C7AF2E8BE452A26F89DDA24B274CEB9E353BE914CA7ACC51EF3DA01.GeneratedTextTransformation.ProcessControllersRecursive(ProjectItem projectItem, AreaInfo area) in c:\Users\Jaap\Projects\MyProject\src\MyProject.Web\Generated\T4MVC.tt:line 676
   at Microsoft.VisualStudio.TextTemplatingB4E831D51904A75E37FAD606F60DF3D4ECAF9D36C4B60E340FDEA400F1A35469B574C0754C7AF2E8BE452A26F89DDA24B274CEB9E353BE914CA7ACC51EF3DA01.GeneratedTextTransformation.ProcessControllersRecursive(ProjectItem projectItem, AreaInfo area) in c:\Users\Jaap\Projects\MyProject\src\MyProject.Web\Generated\T4MVC.tt:line 676
   at Microsoft.VisualStudio.TextTemplatingB4E831D51904A75E37FAD606F60DF3D4ECAF9D36C4B60E340FDEA400F1A35469B574C0754C7AF2E8BE452A26F89DDA24B274CEB9E353BE914CA7ACC51EF3DA01.GeneratedTextTransformation.ProcessAreaControllers(ProjectItems areaFolderItems, AreaInfo area, ProjectItem areaFolder) in c:\Users\Jaap\Projects\MyProject\src\MyProject.Web\Generated\T4MVC.tt:line 637
   at Microsoft.VisualStudio.TextTemplatingB4E831D51904A75E37FAD606F60DF3D4ECAF9D36C4B60E340FDEA400F1A35469B574C0754C7AF2E8BE452A26F89DDA24B274CEB9E353BE914CA7ACC51EF3DA01.GeneratedTextTransformation.ProcessArea(ProjectItem areaFolder, AreaInfo existingArea) in c:\Users\Jaap\Projects\MyProject\src\MyProject.Web\Generated\T4MVC.tt:line 625
   at Microsoft.VisualStudio.TextTemplatingB4E831D51904A75E37FAD606F60DF3D4ECAF9D36C4B60E340FDEA400F1A35469B574C0754C7AF2E8BE452A26F89DDA24B274CEB9E353BE914CA7ACC51EF3DA01.GeneratedTextTransformation.ProcessAreas(Project project) in c:\Users\Jaap\Projects\MyProject\src\MyProject.Web\Generated\T4MVC.tt:line 600
   at Microsoft.VisualStudio.TextTemplatingB4E831D51904A75E37FAD606F60DF3D4ECAF9D36C4B60E340FDEA400F1A35469B574C0754C7AF2E8BE452A26F89DDA24B274CEB9E353BE914CA7ACC51EF3DA01.GeneratedTextTransformation.PrepareDataToRender(TextTransformation tt) in c:\Users\Jaap\Projects\MyProject\src\MyProject.Web\Generated\T4MVC.tt:line 548
   at Microsoft.VisualStudio.TextTemplatingB4E831D51904A75E37FAD606F60DF3D4ECAF9D36C4B60E340FDEA400F1A35469B574C0754C7AF2E8BE452A26F89DDA24B274CEB9E353BE914CA7ACC51EF3DA01.GeneratedTextTransformation.TransformText() in c:\Users\Jaap\Projects\MyProject\src\MyProject.Web\Generated\T4MVC.tt:line 40    Miscellaneous Files c:\Users\Jaap\Projects\MyProject\src\MyProject.Web\Generated\T4MVC.tt   1886
```

**Comment by davidebbo** [comment]
@q42jaap it doesn't look like you have 3.15.4. Is that really what it says at the top?

**Comment by q42jaap** [comment]
<#
/*
T4MVC Version 3.15.4

**Comment by q42jaap** [comment]
It does, I had to restart VS, for some reason...

**Comment by davidebbo** [comment]
Ok, so it works now? The stack you pasted was definitely not running 3.15.4.

**Comment by q42jaap** [comment]
Yes David, sorry about the confusion, there was something strange going on,
it works just fine now!

**Comment by gerwald** [comment]
I just updated the template via NuGet to 3.15.4. and still get the error (also after a restart)
With my 2013 it still works...

```
Severity	Code	Description	Project	File	Line
Error		Running transformation: System.Runtime.InteropServices.COMException (0x80004005): Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.ExternalElements.ExternalCodeFunction.get_FunctionKind()
   at EnvDTE80.CodeFunction2.get_FunctionKind()
   at Microsoft.VisualStudio.TextTemplatingC92F4B6227432FD1150E8D6821C0251F19FF31B64A509D5DC080BECF722A17F1A175F861BC1456C3FB2BB2D0703E6355CAF7852D5F57BC47B9264E8ADCC1C47E.GeneratedTextTransformation.ResultTypeInfo.<.ctor>b__4d(CodeFunction2 f) in c:\XXX\T4MVC.tt:line 1737
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.TextTemplatingC92F4B6227432FD1150E8D6821C0251F19FF31B64A509D5DC080BECF722A17F1A175F861BC1456C3FB2BB2D0703E6355CAF7852D5F57BC47B9264E8ADCC1C47E.GeneratedTextTransformation.ResultTypeInfo..ctor(CodeType codeType) in c:\XXX\T4MVC.tt:line 1736
   at Microsoft.VisualStudio.TextTemplatingC92F4B6227432FD1150E8D6821C0251F19FF31B64A509D5DC080BECF722A17F1A175F861BC1456C3FB2BB2D0703E6355CAF7852D5F57BC47B9264E8ADCC1C47E.GeneratedTextTransformation.ProcessControllerActionMethods(ControllerInfo controllerInfo, CodeClass2 current) in c:\XXX\T4MVC.tt:line 807
   at Microsoft.VisualStudio.TextTemplatingC92F4B6227432FD1150E8D6821C0251F19FF31B64A509D5DC080BECF722A17F1A175F861BC1456C3FB2BB2D0703E6355CAF7852D5F57BC47B9264E8ADCC1C47E.GeneratedTextTransformation.ProcessControllerType(CodeClass2 type, AreaInfo area, DateTime controllerLastWriteTime) in c:\XXX\T4MVC.tt:line 693
   at Microsoft.VisualStudio.TextTemplatingC92F4B6227432FD1150E8D6821C0251F19FF31B64A509D5DC080BECF722A17F1A175F861BC1456C3FB2BB2D0703E6355CAF7852D5F57BC47B9264E8ADCC1C47E.GeneratedTextTransformation.ProcessControllersRecursive(ProjectItem projectItem, AreaInfo area) in c:\XXX\T4MVC.tt:line 625
   at Microsoft.VisualStudio.TextTemplatingC92F4B6227432FD1150E8D6821C0251F19FF31B64A509D5DC080BECF722A17F1A175F861BC1456C3FB2BB2D0703E6355CAF7852D5F57BC47B9264E8ADCC1C47E.GeneratedTextTransformation.ProcessControllersRecursive(ProjectItem projectItem, AreaInfo area) in c:\XXX\T4MVC.tt:line 610
   at Microsoft.VisualStudio.TextTemplatingC92F4B6227432FD1150E8D6821C0251F19FF31B64A509D5DC080BECF722A17F1A175F861BC1456C3FB2BB2D0703E6355CAF7852D5F57BC47B9264E8ADCC1C47E.GeneratedTextTransformation.ProcessAreaControllers(ProjectItems areaFolderItems, AreaInfo area) in c:\XXX\T4MVC.tt:line 591
   at Microsoft.VisualStudio.TextTemplatingC92F4B6227432FD1150E8D6821C0251F19FF31B64A509D5DC080BECF722A17F1A175F861BC1456C3FB2BB2D0703E6355CAF7852D5F57BC47B9264E8ADCC1C47E.GeneratedTextTransformation.ProcessArea(ProjectItems areaFolderItems, String name) in c:\XXX\T4MVC.tt:line 576
   at Microsoft.VisualStudio.TextTemplatingC92F4B6227432FD1150E8D6821C0251F19FF31B64A509D5DC080BECF722A17F1A175F861BC1456C3FB2BB2D0703E6355CAF7852D5F57BC47B9264E8ADCC1C47E.GeneratedTextTransformation.ProcessAreas(Project project) in c:\XXX\T4MVC.tt:line 541
   at Microsoft.VisualStudio.TextTemplatingC92F4B6227432FD1150E8D6821C0251F19FF31B64A509D5DC080BECF722A17F1A175F861BC1456C3FB2BB2D0703E6355CAF7852D5F57BC47B9264E8ADCC1C47E.GeneratedTextTransformation.PrepareDataToRender(TextTransformation tt) in c:\XXX\T4MVC.tt:line 522
   at Microsoft.VisualStudio.TextTemplatingC92F4B6227432FD1150E8D6821C0251F19FF31B64A509D5DC080BECF722A17F1A175F861BC1456C3FB2BB2D0703E6355CAF7852D5F57BC47B9264E8ADCC1C47E.GeneratedTextTransformation.TransformText() in c:\XXX\T4MVC.tt:line 40	Cc.Web	c:\XXX\T4MVC.tt	1737
```

**Comment by gerwald** [comment]
Uninstall and re-install did it for me...
