### ISSUE TITLE
Error when attempting to build in VS2015

### ISSUE THREAD

**Issue by mmoore99** [T4MVC/T4MVC#25]
I have a solution that builds correctly in VS2013.  However, when I attempt to build in VS2015 I get the error listed below. I am using version 3.15.1 of T4MVC. Please advise as to how this can be resolved.

Severity    Code    Description Project File    Line
Error       Running transformation: System.Runtime.InteropServices.COMException (0x80004005): Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo) at Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.ExternalElements.ExternalCodeFunction.get_FunctionKind()
   at EnvDTE80.CodeFunction2.get_FunctionKind()
   at Microsoft.VisualStudio.TextTemplating1588038CA8039F9C7C81600DA8C3D323BCFC80BFBD0EB78C23D0AAF6912A7D4372583F3EC9473008A5AAA97DE08DEF8BD7DA0FE75FA918A46257118B70845271.GeneratedTextTransformation.<GetMethods>b__41(CodeFunction2 f) in c:\Symlinks\Development\VS Projects\FiddleMon\FiddleMon.Web\T4MVC.tt:line 1488
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.VisualStudio.TextTemplating1588038CA8039F9C7C81600DA8C3D323BCFC80BFBD0EB78C23D0AAF6912A7D4372583F3EC9473008A5AAA97DE08DEF8BD7DA0FE75FA918A46257118B70845271.GeneratedTextTransformation.ProcessControllerActionMethods(ControllerInfo controllerInfo, CodeClass2 current) in c:\Symlinks\Development\VS Projects\FiddleMon\FiddleMon.Web\T4MVC.tt:line 832
   at Microsoft.VisualStudio.TextTemplating1588038CA8039F9C7C81600DA8C3D323BCFC80BFBD0EB78C23D0AAF6912A7D4372583F3EC9473008A5AAA97DE08DEF8BD7DA0FE75FA918A46257118B70845271.GeneratedTextTransformation.ProcessControllerType(CodeClass2 type, AreaInfo area, DateTime controllerLastWriteTime) in c:\Symlinks\Development\VS Projects\FiddleMon\FiddleMon.Web\T4MVC.tt:line 771
   at Microsoft.VisualStudio.TextTemplating1588038CA8039F9C7C81600DA8C3D323BCFC80BFBD0EB78C23D0AAF6912A7D4372583F3EC9473008A5AAA97DE08DEF8BD7DA0FE75FA918A46257118B70845271.GeneratedTextTransformation.ProcessControllersRecursive(ProjectItem projectItem, AreaInfo area) in c:\Symlinks\Development\VS Projects\FiddleMon\FiddleMon.Web\T4MVC.tt:line 699
   at Microsoft.VisualStudio.TextTemplating1588038CA8039F9C7C81600DA8C3D323BCFC80BFBD0EB78C23D0AAF6912A7D4372583F3EC9473008A5AAA97DE08DEF8BD7DA0FE75FA918A46257118B70845271.GeneratedTextTransformation.ProcessControllersRecursive(ProjectItem projectItem, AreaInfo area) in c:\Symlinks\Development\VS Projects\FiddleMon\FiddleMon.Web\T4MVC.tt:line 684
   at Microsoft.VisualStudio.TextTemplating1588038CA8039F9C7C81600DA8C3D323BCFC80BFBD0EB78C23D0AAF6912A7D4372583F3EC9473008A5AAA97DE08DEF8BD7DA0FE75FA918A46257118B70845271.GeneratedTextTransformation.ProcessAreaControllers(ProjectItems areaFolderItems, AreaInfo area, ProjectItem areaFolder) in c:\Symlinks\Development\VS Projects\FiddleMon\FiddleMon.Web\T4MVC.tt:line 654
   at Microsoft.VisualStudio.TextTemplating1588038CA8039F9C7C81600DA8C3D323BCFC80BFBD0EB78C23D0AAF6912A7D4372583F3EC9473008A5AAA97DE08DEF8BD7DA0FE75FA918A46257118B70845271.GeneratedTextTransformation.ProcessProjectRoot(Project project) in c:\Symlinks\Development\VS Projects\FiddleMon\FiddleMon.Web\T4MVC.tt:line 577
   at Microsoft.VisualStudio.TextTemplating1588038CA8039F9C7C81600DA8C3D323BCFC80BFBD0EB78C23D0AAF6912A7D4372583F3EC9473008A5AAA97DE08DEF8BD7DA0FE75FA918A46257118B70845271.GeneratedTextTransformation.PrepareDataToRender(TextTransformation tt) in c:\Symlinks\Development\VS Projects\FiddleMon\FiddleMon.Web\T4MVC.tt:line 553
   at Microsoft.VisualStudio.TextTemplating1588038CA8039F9C7C81600DA8C3D323BCFC80BFBD0EB78C23D0AAF6912A7D4372583F3EC9473008A5AAA97DE08DEF8BD7DA0FE75FA918A46257118B70845271.GeneratedTextTransformation.TransformText() in c:\Symlinks\Development\VS Projects\FiddleMon\FiddleMon.Web\T4MVC.tt:line 40 FiddleMon.Web   c:\Symlinks\Development\VS Projects\FiddleMon\FiddleMon.Web\T4MVC.tt    1488

**Comment by davidebbo** [comment]
Strange, as it sounds the same as #24, which I just fixed in 3.15.1.

**Comment by davidebbo** [comment]
I see, my fix was not general enough. Made a new one. Can you try 3.15.2?

**Comment by mmoore99** [comment]
3.15.2 did indeed solve the problem.  Thanks for the quick response.
